version: "3"
services:
  app:
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ".:/app"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    restart: always

volumes:
  postgresql-volume:
  # app:
# x-mutagen:
#   sync:
#     defaults:
#       mode: "two-way-resolved"
#       ignore:
#         vcs: true
#     app:
#       alpha: "."
#       beta: "volume://app"
